[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.setuptools", "python311Packages.wheel"]

[phases.install]
cmds = ["python3.11 -m pip install -r requirements.txt --no-cache-dir"]

[phases.build]
cmds = ["echo 'Build phase completed'"]

[start]
cmd = "gunicorn --bind 0.0.0.0:$PORT app:app"

