[phases.setup]
nixPkgs = [
  "python311Full"
]

[phases.install]
cmds = [
  "python3.11 --version",
  "python3.11 -m pip install --upgrade pip setuptools wheel",
  "python3.11 -m pip install -r requirements.txt --no-cache-dir"
]

[phases.build]
cmds = ["echo 'Build phase completed'"]

[start]
cmd = "gunicorn --bind 0.0.0.0:$PORT app:app"
